image: Ubuntu2204  # образ для сборки

stack: node 20  # окружение

branches:
  only:
    - master  # ветка git
    - main

cache: node_modules  # кеширование

install:
  - npm  # команда установки зависимостей

build: off  # отключаем встроенную в appveyor систему сборки

build_script:
  - npm run build   # команда сборки

test_script:
  - npm run lint && npm test  # скрипт тестирования
